### PR TITLE
Hacl hashes

### PR DESCRIPTION
**Pull request by karthikbhargavan**
This draft PR adds code for all four SHA-2 variants. 
The code still needs to be tested and benchmarked.
Once this succeeds, a follow-up full PR will add SHA-3 and BLAKE2.

### CODE REVIEW

**Comment by ignatk** [comment]
I see we're modifying the generic implementation of sha512 in the Linux kernel. I suggest for now creating a separate "driver" (for example `sha512-hacl`) and leave the generic implementation as is. This will allow us to compare performance of the two implementations side-by-side.

On top of the above - to replace the generic in-kernel implementation upstream would request us to test it on all possible architectures (and not just x86/arm64).

**Comment by karthikbhargavan** [comment]
So, do you suggest we put sha256-hacl and sha512-hacl in /crypto, leaving the current code in the kernel unchanged? 
If we do so, our code would not be used by the kernel in any way or be tested within the kernel.
Should we still try to link it to the kernel hash APIs? We may need some help to do this properly.

**Comment by ignatk** [comment]
> If we do so, our code would not be used by the kernel in any way or be tested within the kernel

Linux Crypto API is modular and you can have several implementations of the same algorithm (and the kernel actually has). So `sha256-hacl` can be yet another implementation. To integrate it with Linux Crypto API we just need some boilerplate code, which can be copied from other implementations. For sha see below

https://github.com/cloudflareresearch/linux/blob/6ae51ffe5e768d9e25a7f4298e2e7a058472bcc3/crypto/sha512_generic.c#L178-L227

Basically, some of this is standard kernel module boilerplate code (init, exit funcs as well as `MODULE_LICENSE()`/`MODULE_DESCRIPTION()`

For Crypto API specifics
`MODULE_ALIAS_CRYPTO()` will declare which crypto algorithm we are implementing (so the system can find it later)
Notice there are two definitions per algorithm: the first one describes the algorithm itself (so this definition is same across all implementations) and the second one describes uniquely our specific driver ("sha512-generic" above, so for us it would be something like "sha512-hacl"). Some kernel users may request a particular implementation by explicitly using the driver name.

And finally we declare a `struct shash_alg` structure, which has pointers to callbacks implementing the algorithm. We register/unregister this structure in the init/exit funcs.

So, if we do all the above, this implementation would be a "drop-in" for any other kernel sha implementation. We can compile it as a kernel module as well as integrate it in to the Linux Kernel via Kbuild.

**Comment by karthikbhargavan** [comment]
Thanks for the links and explanation! We'll give it a go.

**Pull request closed without merging**
